name: vrit_birthday
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  async_wallpaper: ^2.0.3
  bloc: ^8.1.2
  cloud_firestore: ^4.17.5
  dio: ^5.4.3+1
  firebase_auth: ^4.20.0
  firebase_core: ^2.32.0
  firebase_messaging: ^14.9.4
  firebase_storage: ^11.7.7
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_hooks: ^0.20.5
  flutter_local_notifications: ^17.1.2
  flutter_localizations:
    sdk: flutter
  google_sign_in: ^6.2.1
  http: ^1.2.1
  intl: ^0.19.0
  sign_in_with_apple: ^6.1.0

dev_dependencies:
  bloc_test: ^9.1.2
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
