// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show TargetPlatform, defaultTargetPlatform, kIsWeb;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBupIlZijerUypomAJ3SSPHXgJatQtgzus',
    appId: '1:517279909339:web:37b102e04427f57adcd3fe',
    messagingSenderId: '517279909339',
    projectId: 'vritphotos',
    authDomain: 'vritphotos.firebaseapp.com',
    storageBucket: 'vritphotos.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDI8Ir6ZttqR7ffv3RNFATB9IHU00NAMQ',
    appId: '1:517279909339:android:c156e1477c9407bddcd3fe',
    messagingSenderId: '517279909339',
    projectId: 'vritphotos',
    storageBucket: 'vritphotos.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVKtTFVJg1zjoxSo8HIgoA8Yn72R6WPbw',
    appId: '1:517279909339:ios:2b8a572e689e6c4cdcd3fe',
    messagingSenderId: '517279909339',
    projectId: 'vritphotos',
    storageBucket: 'vritphotos.appspot.com',
    iosBundleId: 'com.vrit.vrit-birthday',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBupIlZijerUypomAJ3SSPHXgJatQtgzus',
    appId: '1:517279909339:web:ff4a82b24ecb1c79dcd3fe',
    messagingSenderId: '517279909339',
    projectId: 'vritphotos',
    authDomain: 'vritphotos.firebaseapp.com',
    storageBucket: 'vritphotos.appspot.com',
  );
}
