// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCo6Y4jdj0DM_4eiM3NwZTf12FEv-bWUS0',
    appId: '1:1028615433437:web:979f46ab3ddd8fae877f34',
    messagingSenderId: '1028615433437',
    projectId: 'vrinter',
    authDomain: 'vrinter.firebaseapp.com',
    storageBucket: 'vrinter.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmlsqgacZsqyefVpBOX8vhF7pACFby80g',
    appId: '1:1028615433437:android:97687466e71eb241877f34',
    messagingSenderId: '1028615433437',
    projectId: 'vrinter',
    storageBucket: 'vrinter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPOgGG3PiHn651OvL8ah_MthedsTR1l_g',
    appId: '1:1028615433437:ios:bc7b09c42ee659fe877f34',
    messagingSenderId: '1028615433437',
    projectId: 'vrinter',
    storageBucket: 'vrinter.appspot.com',
    iosBundleId: 'com.vrit.vrit-birthday',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPOgGG3PiHn651OvL8ah_MthedsTR1l_g',
    appId: '1:1028615433437:ios:127d3eaceae800a8877f34',
    messagingSenderId: '1028615433437',
    projectId: 'vrinter',
    storageBucket: 'vrinter.appspot.com',
    iosBundleId: 'com.vrit.app',
  );
}
